name: app_movil
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
    # Networking
  dio: ^5.3.0
    
  sqflite: ^2.3.0
  path: ^1.8.3
    
    # GestiÃ³n de Estado
  provider: ^6.0.5
    
    # Guardar IP simple
  shared_preferences: ^2.2.0
  mobile_scanner: ^3.5.5

  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
